menu:
- {name: 'Publications', url: '/publications'}
#- {name: 'courses', url: '/courses'}
#- {name: 'cv', url: '/cv'}
#- {name: 'contact', url: '/contact'}

social:
- {icon: 'github', link: 'https://github.com/parkyg01'}
#- {icon: 'twitter', link: 'https://twitter.com/paululele'}
#- {icon: 'instagram', link: 'https://instagram.com/paululele'}
#- {icon: 'linkedin', link: 'https://linkedin.com/in/lenpaul'}

institution_address: '77, Cheongam-ro, Nam-gu, Pohang-si, Gyeongsangbuk-do, Republic of Korea 37673'
phone: '+82-10-4857-0727'
email: 'yg.park@postech.ac.kr'
office: 'Room 4304, RIST 4'
